version: '3.9'

services:
  app:
    build: ./
    container_name: korpus-api
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
  db:
    image: mysql:8.0.31
    container_name: korpus-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'korpus_password'
      MYSQL_PASSWORD: 'korpus_password'
      MYSQL_USER: 'korpus_user'
      MYSQL_DATABASE: 'korpus_db'
    ports:
      - "3306:3306"
    volumes:
      - korpus-data:/var/lib/mysql

volumes:
  korpus-data:
    name: korpus-data
