"""poebalisya i hvatit

Revision ID: 184aad91834d
Revises: ed4544245246
Create Date: 2020-02-02 18:13:37.719825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184aad91834d'
down_revision = 'ed4544245246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chat_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'chat_id')
    # ### end Alembic commands ###
