"""empty message

Revision ID: 1e180ea67ba8
Revises: 243013fb3130
Create Date: 2020-01-12 17:48:35.196279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e180ea67ba8'
down_revision = '243013fb3130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chat_id', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('state', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'state')
    op.drop_column('user', 'chat_id')
    # ### end Alembic commands ###
