"""empty message

Revision ID: 243013fb3130
Revises: 4942c3e2eb3c
Create Date: 2020-01-12 13:49:22.887280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243013fb3130'
down_revision = '4942c3e2eb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('user_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_statuses')
    op.drop_table('statuses')
    # ### end Alembic commands ###
