"""Adding Questionnaire tables

Revision ID: 27dca0ccb33d
Revises: a46f3f6cb0ef
Create Date: 2020-01-03 15:37:27.563381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27dca0ccb33d'
down_revision = 'a46f3f6cb0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaire_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('question_num', sa.Integer(), nullable=True),
    sa.Column('question_answ', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('membership', sa.Column('role_id', sa.Integer(), nullable=True))
    op.alter_column('membership', 'team_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('membership', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('membership', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('membership', 'team_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('membership', 'role_id')
    op.drop_table('questions_types')
    op.drop_table('questions')
    op.drop_table('questionnaire_info')
    op.drop_table('questionnaire')
    # ### end Alembic commands ###
