"""empty message

Revision ID: 288dd230e5b2
Revises: 2d7dc10a2168
Create Date: 2020-04-19 01:08:36.867427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288dd230e5b2'
down_revision = '2d7dc10a2168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voting', sa.Column('voting_id', sa.Integer(), nullable=True))
    op.add_column('voting_table', sa.Column('month', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voting_table', 'month')
    op.drop_column('voting', 'voting_id')
    # ### end Alembic commands ###
