"""Voting

Revision ID: 2d8a079ccf9a
Revises: e75568c58776
Create Date: 2020-01-22 09:27:23.508508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8a079ccf9a'
down_revision = 'e75568c58776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion', sa.Column('axis_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criterion', 'axis_id')
    # ### end Alembic commands ###
