"""adding fb inst vk urls

Revision ID: 369d47561eb3
Revises: 1f5ee611fcdc
Create Date: 2020-02-09 17:22:57.672938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369d47561eb3'
down_revision = '1f5ee611fcdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fb_url', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('inst_url', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('vk_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'vk_url')
    op.drop_column('user', 'inst_url')
    op.drop_column('user', 'fb_url')
    # ### end Alembic commands ###
