"""users deleted team/roles

Revision ID: 3f3ff640f4cb
Revises: 9ae2fa9439f7
Create Date: 2020-01-03 17:16:30.117842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f3ff640f4cb'
down_revision = '9ae2fa9439f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'team')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('team', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
