"""private_key

Revision ID: 48326c5c4f86
Revises: 
Create Date: 2021-10-02 04:08:30.503735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48326c5c4f86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('private_key', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'private_key')
    # ### end Alembic commands ###
