"""is budget record saved to blockchain

Revision ID: 50217b025181
Revises: 48326c5c4f86
Create Date: 2021-10-02 15:05:26.827303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50217b025181'
down_revision = '48326c5c4f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_record', sa.Column('is_saved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_record', 'is_saved')
    # ### end Alembic commands ###
