"""статусы

Revision ID: 564b0618a0a2
Revises: df8bbc640d66
Create Date: 2020-01-10 14:46:10.744854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564b0618a0a2'
down_revision = 'df8bbc640d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('user_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_statuses')
    op.drop_table('statuses')
    # ### end Alembic commands ###
