"""User added tg_id

Revision ID: 5d356e8f376c
Revises: 27dca0ccb33d
Create Date: 2020-01-03 16:00:22.927122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d356e8f376c'
down_revision = '27dca0ccb33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tg_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tg_id')
    # ### end Alembic commands ###
