"""Добавил 'assessment' в Questionnaire

Revision ID: 84c804734e6e
Revises: ebd22c37b3b1
Create Date: 2020-04-10 20:41:15.676583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c804734e6e'
down_revision = 'ebd22c37b3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire', sa.Column('assessment', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaire', 'assessment')
    # ### end Alembic commands ###
