"""adding questionnaire id

Revision ID: 971a4bc23dca
Revises: 3f3ff640f4cb
Create Date: 2020-01-03 17:48:50.947027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971a4bc23dca'
down_revision = '3f3ff640f4cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire_info', sa.Column('questionnaire_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaire_info', 'questionnaire_id')
    # ### end Alembic commands ###
