"""adding two columns in Questionnaire

Revision ID: 9ae2fa9439f7
Revises: 5d356e8f376c
Create Date: 2020-01-03 16:46:11.885236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae2fa9439f7'
down_revision = '5d356e8f376c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('questionnaire', sa.Column('team_id', sa.Integer(), nullable=False))
    op.add_column('questionnaire', sa.Column('type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaire', 'type')
    op.drop_column('questionnaire', 'team_id')
    op.drop_column('questionnaire', 'date')
    # ### end Alembic commands ###
