"""empty message

Revision ID: e6eb20b9e687
Revises: c9a08c9df9c5
Create Date: 2020-01-26 14:53:47.659863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6eb20b9e687'
down_revision = 'c9a08c9df9c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion', sa.Column('axis_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criterion', 'axis_id')
    # ### end Alembic commands ###
